# Copyright 2026 symphony authors
# SPDX-License-Identifier: Apache-2.0

[package]
name = "symphony"
version = "0.1.0"

[application]
supervisor = "SymphonySupervisor"

[dependencies]
http = { git = "https://github.com/jamesc/beamtalk-http", tag="v0.1.0" }
yaml = { git = "https://github.com/jamesc/beamtalk-yaml", branch = "main" }
